const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');
const moment = require('moment');

const getRevenuesheetData = async function () {
    // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
    const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: process.env.REVENUE_SERVICE_EMAIL,
        key: Buffer.from(process.env.REVENUE_PRIVATE_KEY, 'base64').toString(
            'utf-8'
        ),
        scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });
    // Initialize the sheet - doc ID is the long id in the sheets URL
    const doc = new GoogleSpreadsheet(
        process.env.REVENUE_SHEET_DOC_ID,
        serviceAccountAuth
    );

    await doc.loadInfo(); // loads document properties and worksheets
    const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    await sheet.loadHeaderRow();
    const rows = await sheet.getRows();
    return rows.map((row) => {
        if (!row.get('date')) return undefined;
        return {
            date: new Date(row.get('date')),
            client: row.get('Opdrachtgever'),
            kind: row.get('Soort werk'),
            description: row.get('Omschrijving activiteit'),
            amount: parseFloat(row.get('amount')),
            words: parseInt(row.get('Aantal woorden')) || undefined,
            hours: parseFloat(row.get('Aantal uren')) || undefined,
            payed: row.get('Betaald?') == 'Ja' ? true : false,
            projectnr: row.get('Projectnummer') || undefined,
            tariff: row.get('Tarief') || undefined,
        };
    });
};

const writeInflux = function (influxClient, data) {
    for (const datapoint of data) {
        if (!datapoint) continue;
        const { date, projectnr, client, kind, ...fields } = datapoint;

        const timestamp = moment(date).add(12, 'hours');
        influxClient
            .write('revenue')
            .time(timestamp.format('x') * 1000000)
            .field(fields)
            .tag('projectnr', projectnr)
            .tag('kind', kind)
            .tag('client', client)
            .queue();
    }
    return influxClient
        .syncWrite()
        .then(() => console.debug(`${Date.now()} revenuesheet: write success`))
        .catch((err) =>
            console.error(
                `${Date.now()} revenuesheet: write failed ${err.message}`
            )
        );
};

const logRevenuesheet = async (influxClient) => {
    const data = await getRevenuesheetData();
    return writeInflux(influxClient, data);
};

module.exports = logRevenuesheet;
